---
title: "QMEE 2021"
author: "Ali"
date: "14/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Calss 1 
- R basics

```{r}
x <- 1
## vector
words <- c("hello", "a")
v <- 1:5
xx <- c(1,"hello") ## ? coercion
str(xx)
## turned 1 to a char to make them the same type

## lists
L <- list(1,"hello")
L[[1]]


```

## Calss 2

- we are going to continue intro to R
- then github with JD

```{r intro to R}
x <- c(2,3,1)
y <- c(2,2,6)
t.test(x,y,var.equal=T)

# R is case sensative m and M are diff
# tab is your friend, type v and tab and R shows you everything starts with v
# no space in var name, what is the best var name? not long, long enough
# Read the style points in the course page

# we talked about vector and lists, more complicated objects

# dataframe, list of columns, each col is a vector, rows are observations
dd <- data.frame(a=1:3,b=c("hello", "good", "bad"))

factor(c("sparrow","robin","bat"))## is different from c()
species <- c("sparrow","robin","bat")
# Note: most of variables are numerics or factors
# another kind of dataframe called tibble

## Loops
 v<- 1:5
for(x in v){
  if(x>=4)
    print(x^2)
}

 ## Logical
 x=1
  x!=2 ## bang
  x==1 & 3==5
 x==1 | 3==5
 species == "robin" ## is applied to the whole vector

 # we want to refer to a specific element
 species[2]
 # a row from a df, several ways:
 dd[["a"]]
 dd$a ## shortcut
 dd[[1]] ## refering to element by position

# ########################################
## The tidyverse (by Hadly Wicom)
# ########################################
 library(tidyverse)
 # a set of packages, can be easier to do complicated things, speed
 # disadvantages: instability with base R
 # where are you putting your stuff, data
 getwd()
 dir.create("data") ## make sure you are in the dir of your course where you want to creat a data dir
 download.file(url="https://ndownloader.figshare.com/files/2292169",
               destfile = "data/newdata.csv")

 surveys <- read_csv("data/newdata.csv")
## it is a tibble
 head(surveys)

## manipulating data verbs: select (taking col), filter (taking rows), ..
 select(surveys, month, day)
 select(surveys,-genus)


 filter(surveys, (month >11|month<3) & species== "albigula")  ## if you put , in filter it means & &
 ## PIPE

 survey2 <- (surveys
   %>% filter(month >11)
   %>% select(-day)
   %>% mutate(LW=weight/100) ## to change the name of var or creat a new var
 )

 # keyboard shortcut, go to helpyboard shortcut keys
 # %>% ctrl + shift +m

# other verbs; group_by(), summerise()

```

## Calss 3

Date: Jan 21, 2021
see chap 9 and 10 of https://happygitwithr.com/

```{r intro to R class 3}
## villageTable <- read_csv("/data/villageTable.csv")
## where is this data? 



```


